alias c='xclip -selection clipboard &>/dev/null'
alias g='gvim'
alias p='xclip -o -selection clipboard'
alias s='tmux save-buffer - |c'
alias v='vim'

alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gd='git diff'
alias gf='git fetch'
alias go='git checkout'
alias gs='git status'
